### ISSUE TITLE
New upstream release

### ISSUE THREAD

**Issue by soaringowl2145** [flathub/net.runelite.RuneLite#10]
The current release is 1.6.29.  Please update the flatpak.

Also can you please update the flatpak to use the latest org.freedesktop.Platform to 20.08?

Freedesktop Platform - Shared libraries   org.freedesktop.Platform            20.08

**Comment by rushsteve1** [comment]
> The current release is 1.6.29. Please update the flatpak.

This flatpak is versioned off of the [RuneLite Launcher](https://github.com/runelite/launcher), not RuneLite itself since the launcher takes care of updating that and OSRS. There has not been an update to the Launcher, but I'll update the dependencies.
