### ISSUE TITLE
Verify this flatpak on the beta flathub website

### ISSUE THREAD

**Issue by Felanbird** [flathub/net.runelite.RuneLite#24]
Flathub currently has a verification process (only available on the beta website) to give you a ☑️ if the website related to your flatpak, confirms your flatpak is verified by the developers. 
As the odd person comes into the Runelite discord to ask if the flatpak build is legit, I believe this could be helpful (to at least the ones using the beta).

The verification process is as follows:

1. Log into https://beta.flathub.org/
2. Find your way to your developed projects page (I don't have the link for that)
3. Select `Developer Settings` under the `Runelite` project
![flathub-chatterino](https://user-images.githubusercontent.com/41973452/224566069-9d7306f4-a2ad-4896-baf1-5ac146443b70.png)
4. Follow the steps listed

The steps should require you to deploy a page to a specified subdomain, and said page just displays the code given.

A verified project to compare can be found here https://beta.flathub.org/apps/com.chatterino.chatterino
and the related PR can be found here https://github.com/Chatterino/website/pull/154

**Comment by Felanbird** [comment]
Discussed in the discord, came to a conclusion that not now, maybe once it's not only-beta and a few other things are changed. 👍

**Comment by Nightfirecat** [comment]
We're hesitant to do so because we don't own the repository from which it is published.
