### ISSUE TITLE
Links from OSRS don't open the browser

### ISSUE THREAD

**Issue by Emerald-glitch** [flathub/net.runelite.RuneLite#29]
The links from to runelite client work but the links from osrs client like buying membership, etc currently do nothing. 

It seems it is due to missing gvfs libraries in freedesktop platform. 

 An easy solution would be just switching to gnome.Platform. This is what i am suggesting, as a bonus we can even drop libnotify after switching to gnome.Platform.

We also need to enable "org.gtk.vfs.*" session bus, xdg-open/gvfs and xdg-open/gvfsd filesystem for it to work correctly.

you can try it out with

`flatpak run --talk-name=org.gtk.vfs.* --filesystem=xdg-run/gvfsd --filesystem=xdg-run/gvfs --runtime=org.gnome.Platform/x86_64/44 net.runelite.RuneLite`

**Comment by Adam-** [comment]
This is due to https://bugs.openjdk.org/browse/JDK-8275494

**Comment by Emerald-glitch** [comment]
> This is due to https://bugs.openjdk.org/browse/JDK-8275494

it doesn't seem like the same issue though. The JDK bug report talks about the file opening after the app exits. but in case of osrs, clicking on lings just do nothing. But with proper filesystemand sbus access and gnome runtime it does work as it is supposed to.

**Comment by Felanbird** [comment]
@Emerald-glitch Are you still able to replicate this issue? It may have been resolved via https://github.com/runelite/runelite/commit/893af12e1d2d6a9c981a6f9d796a822886efe35e

**Comment by Adam-** [comment]
This should definitely be resolved via https://github.com/runelite/runelite/commit/893af12e1d2d6a9c981a6f9d796a822886efe35e. Reopen if it is still an issue.

**Comment by Emerald-glitch** [comment]
@Felanbird sorry, i didn't get the notification about your comment. And yeah i can confirm it is working.
