### ISSUE TITLE
Update the runtime

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/net.runelite.RuneLite#40]
If possible, update the [runtime](https://github.com/flathub/net.runelite.RuneLite/blob/master/net.runelite.RuneLite.json#L4) used by this Flatpak to a latest stable 23.08 one.

/cc @Adam-

**Comment by AsciiWolf** [comment]
@Adam- Any update about the update? :-)

**Comment by Adam-** [comment]
> @Adam- Any update about the update? :-)

If you want to make a pull request to update the runtime I am happy to merge it.

**Comment by AsciiWolf** [comment]
Done.
